### ISSUE TITLE
Allow go forward in day view

### ISSUE THREAD

**Issue by CarsonCook** [EngSoc-IT-Team/QTap#20]

**Comment by CarsonCook** [comment]
using agenda view instead of day view, so this is obsolete

**Comment by CarsonCook** [comment]
Or is it scrollable down when there are events?

**Comment by ruffoa** [comment]
Day view can already be navigated forward / back a day by swiping from left to right / right to left along the Date area on the top bar as shown ![QTap Image](https://lh3.googleusercontent.com/Z91xZBILB17m0S9L4EwEjtQQv3GWgnu0-eYJxz7ludb7h0dSj9yRV44RYDHADWLKogZPZpNAOxej61cV9zWyDJj_IylAp6LX38OfR00TU6mOlOiv9gfG3S8kedZeizpiUORQAgh19-00OqGv7mtwnry8d-XKsIds1z3vibHMIfRhdQ5zEHuDHiMZ2tbXkay-S_LSkoa2FdBw0Vwj2l3r1z39AVDiQUPdvNBwaFO9BO7xsSakh_LUzvoPL--YjGew18ao91hqZ-AoIsOiVkQ0gqssJLQyIDU-raXxJ6XzG7D3USjp8fTcn6gTS_N49DMc94XwH8f8jiBvmThBvQMYtH9Wai3I9XmepZiL7__Who4P0KvrtKn8XBsjpcmlJCBswRLO5suYZgii6a_JmzNuQEwSUJgPDFahC7iSXitVvFt14_iFzNY7FrwJTBXCYq9qkT1jdA2vYBXt_5UTaXs5LqmGrPFOeF9KqZDeWfCYnXB3SrwC-YRCjasyqm-RVX2mrJaIM7TC3Zi4LBarOTy85dviXfvDc7QtWV2PdHoVwVAuoESUfn8S8cKdI74Gx6clxcoFqFF0rs9ioFOE-x2y7YSmy9pyp-T6AVqoiF9kDlAeT2cgzTh8Q2ghEveqCf9DvzdxH2lO_BEYfu242vQlLOY3le2OpD_itReAzsJzMp4=w332-h589-no)
