### ISSUE TITLE
have map go to current location automatically

### ISSUE THREAD

**Issue by CarsonCook** [EngSoc-IT-Team/QTap#32]

**Comment by ruffoa** [comment]
This now defaults to the last known user position within location service.  This helps load the map quicker, and should be close to the right location the majority of the time.  
Future improvement: have this update later to the actual (current) position of the user.

**Comment by CarsonCook** [comment]
don't want - there is a button to go to current location, and this way would require location to be on/permission given, whereas currently we don't need those things.
