### ISSUE TITLE
First run doesnt act like first run

### ISSUE THREAD

**Issue by CarsonCook** [EngSoc-IT-Team/QTap#79]
welcome screens don't show unless data cleared
schedule not downloaded unless log out and back in

**Comment by ruffoa** [comment]
This is a feature; the app automatically backs up all data to Google Drive on Android 6.0+ devices and restores the data on reinstall.  We probably want this, as if the user reinstalls the app they are automatically logged in, and if the database is still less than one week old, it is used as valid data, if not the schedule is automatically downloaded.

I have modified the logout function to cause the app to show the welcome screens on logout.

**Comment by CarsonCook** [comment]
Still issues on first run after install (for me after clearing data, uninstall, run from AS)

**Comment by ruffoa** [comment]
Clearing data is irrelevant I believe, as the app data is simply downloaded
on launch.  You have to physically delete the backup on your Google
account, or use the logout button to reinitialize the app, this clearing
the backups.
